### ISSUE TITLE
State Diagram

### ISSUE THREAD

**Issue by valejin** [valejin/StudyPal#6]
prima versione di state diagram
![stateDiagram_GestisciPrenotazioni_v1_page-0001](https://github.com/user-attachments/assets/a3bbd306-7daf-4d36-b710-77757443b8b3)

**Comment by bytelisa** [comment]
Le frecce per tornare indietro hanno verso sbagliato (da Dettagli Richiesta verso start). Dopo controllo se c'è altro

**Comment by valejin** [comment]
state diagram (versione 2
![stateDiagram_GestisciPrenotazioni_v2_page-0001](https://github.com/user-attachments/assets/bfb07f3e-d742-4b75-b1f1-06db36359eee)
)

**Comment by bytelisa** [comment]
Occhio alla maiuscola nel secondo stato

**Comment by bytelisa** [comment]
![state_PrenotaRipetizione](https://github.com/user-attachments/assets/d91c611b-76ad-4cba-a57a-59fd1d448146)

**Comment by valejin** [comment]
![stateDiagram_GestisciRichieste_v8_page-0001](https://github.com/user-attachments/assets/662f0d17-97ca-4d26-8a8c-0beda9bbfb5d)
vesione finale
